swing_foot: left
#swing_foot: right

# Initialization
#initial_jpos: [0.02, -1.1, 1.6, -0.02, -1.1, 1.6]
initial_jpos: [0.02, -0.92, 1.55, -0.02, -0.93, 1.59]
body_height: 0.85

# Timing Parameters (sec)
jpos_initialization_time: 1.3
body_lifting_time: 2.0

# Timing Parameters (sec)
stance_time: 1.0
transition_time: 0.1
moving_preparation_time: 1.0
swing_duration: 100.

# Trajectory
swing_height: 0.2
# amplitude: [0.0, 0.0, 0.05]
amplitude: [0, -0.0, 0.0]
frequency: [0.0, 1.0, 1.0]
phase: [0., 0.,  0.]

